# Set programs that you use
$terminal = kitty
$fileManager = nautilus
$menu = rofi -show drun
$browser = vivaldi
$hypridle = hypridle
$lockscreen = hyprlock
$hyprsunset = hyprsunset
$font = CaskaydiaCove Nerd Font Mono
